# Generated by Django 5.2 on 2025-05-05 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('subhead', models.CharField(blank=True, max_length=255, null=True)),
                ('blurb', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('regenerate_slug', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('raw_age', models.IntegerField(blank=True, default=None, null=True)),
                ('current_position', models.CharField(max_length=255, null=True)),
                ('current_school', models.CharField(max_length=255, null=True)),
                ('current_country', models.CharField(max_length=255, null=True)),
                ('mlb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('regenerate_slug', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerRankingCarryingTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('tool', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=5)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['tool', '-score'],
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.CharField(max_length=255)),
                ('ranking_type', models.CharField(blank=True, choices=[('College', 'College'), ('High School', 'High School'), ('International', 'International')], max_length=255, null=True)),
                ('ranking_length', models.CharField(blank=True, max_length=255, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_mock_draft', models.BooleanField(default=False)),
                ('mock_draft_version', models.CharField(blank=True, max_length=255, null=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('regenerate_slug', models.BooleanField(default=False)),
                ('subhead', models.CharField(blank=True, max_length=255, null=True)),
                ('blurb', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', 'is_final', '-ranking_length'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('ranking_position', models.CharField(blank=True, max_length=255, null=True)),
                ('ranking_school', models.CharField(blank=True, max_length=255, null=True)),
                ('ranking_country', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, choices=[('College', 'College'), ('High School', 'High School'), ('International', 'International')], max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=10, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='overslot.player')),
                ('carrying_tools', models.ManyToManyField(blank=True, to='overslot.playerrankingcarryingtool')),
                ('ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='overslot.ranking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
