# Generated by Django 5.2 on 2025-05-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerranking',
            options={'ordering': ['rank', 'ranking', 'player']},
        ),
        migrations.AddField(
            model_name='player',
            name='scouting_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
