# Generated by Django 5.2 on 2025-05-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0002_alter_playerranking_options_player_scouting_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
