# Generated by Django 5.2 on 2025-05-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0003_article_publish_alter_player_current_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='playerranking',
            options={'ordering': ['player', 'ranking', 'rank']},
        ),
        migrations.AddField(
            model_name='article',
            name='players',
            field=models.ManyToManyField(blank=True, to='overslot.player'),
        ),
    ]
