# Generated by Django 5.2 on 2025-05-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0004_alter_article_options_alter_playerranking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerranking',
            options={'ordering': ['ranking', 'rank']},
        ),
        migrations.AlterField(
            model_name='playerranking',
            name='role',
            field=models.CharField(blank=True, choices=[('40', '40'), ('45', '45'), ('50', '50'), ('55', '55'), ('60', '60'), ('65', '65'), ('70', '70'), ('75', '75'), ('80', '80')], max_length=10, null=True),
        ),
    ]
