# Generated by Django 5.2 on 2025-05-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0005_alter_playerranking_options_alter_playerranking_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='current_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='current_school',
            new_name='school',
        ),
        migrations.AddField(
            model_name='player',
            name='bats',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hometown',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='throws',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
