# Generated by Django 5.2 on 2025-05-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0006_rename_current_country_player_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerranking',
            old_name='ranking_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='playerranking',
            old_name='ranking_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='playerranking',
            old_name='ranking_school',
            new_name='school',
        ),
        migrations.AddField(
            model_name='playerranking',
            name='commitment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='raw_carrying_tools',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='risk',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
