# Generated by Django 5.2 on 2025-05-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0007_rename_ranking_country_playerranking_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
