# Generated by Django 5.2 on 2025-05-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0008_player_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='scouting_report',
        ),
        migrations.AddField(
            model_name='player',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='scouting_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
