# Generated by Django 5.2 on 2025-05-26 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0010_article_authors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('display_name', models.CharField(help_text='Name to display on articles', max_length=255)),
                ('email', models.EmailField(help_text='Public contact email (if different from login email)', max_length=254)),
                ('bio', models.TextField(blank=True, help_text='Author biography', null=True)),
                ('twitter', models.CharField(blank=True, help_text='Twitter handle (without @)', max_length=255, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='articles', to='overslot.author'),
        ),
    ]
