# Generated by Django 5.2 on 2025-05-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0011_author_alter_article_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bluesky',
            field=models.CharField(blank=True, help_text='Bluesky handle (with or without @)', max_length=255, null=True),
        ),
    ]
