# Generated by Django 5.2 on 2025-06-15 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0013_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('decision', models.CharField(choices=[('merged', 'Merged - players are the same person'), ('separate', 'Separate - players are different people')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the decision', null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_decisions_as_player1', to='overslot.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_decisions_as_player2', to='overslot.player')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('player1', 'player2')},
            },
        ),
    ]
