# Generated by Django 5.2 on 2025-06-16 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0014_duplicatedecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatedecision',
            name='primary_player',
            field=models.ForeignKey(blank=True, help_text='For merged decisions, which player was kept as primary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_decisions_as_primary', to='overslot.player'),
        ),
    ]
