# Generated by Django 5.2 on 2025-06-16 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0015_duplicatedecision_primary_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialDuplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('similarity_score', models.FloatField(help_text='Similarity score between 0 and 1')),
                ('match_reasons', models.JSONField(default=list, help_text='List of reasons why these might be duplicates')),
                ('player1_name', models.CharField(max_length=255)),
                ('player2_name', models.CharField(max_length=255)),
                ('player1_school', models.CharField(blank=True, max_length=255, null=True)),
                ('player2_school', models.CharField(blank=True, max_length=255, null=True)),
                ('player1_state', models.CharField(blank=True, max_length=255, null=True)),
                ('player2_state', models.CharField(blank=True, max_length=255, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_duplicates_as_player1', to='overslot.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_duplicates_as_player2', to='overslot.player')),
            ],
            options={
                'ordering': ['-similarity_score', 'player1_name', 'player2_name'],
                'indexes': [models.Index(fields=['similarity_score'], name='overslot_po_similar_84d42f_idx'), models.Index(fields=['player1_name'], name='overslot_po_player1_9d5a98_idx'), models.Index(fields=['player2_name'], name='overslot_po_player2_cb0c1b_idx')],
                'unique_together': {('player1', 'player2')},
            },
        ),
    ]
