# Generated by Django 5.2 on 2025-06-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0016_potentialduplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='mock_team',
            field=models.CharField(blank=True, help_text='Team that drafted this player in mock draft', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='mock_team_logo_url',
            field=models.CharField(blank=True, help_text="URL to the team's logo image", max_length=255, null=True),
        ),
    ]
