# Generated by Django 5.2 on 2025-06-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0017_playerranking_mock_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the article', null=True, upload_to='articles/featured/'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the ranking', null=True, upload_to='rankings/featured/'),
        ),
    ]
