# Generated by Django 5.2 on 2025-06-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0018_article_featured_image_ranking_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
