# Generated by Django 5.2 on 2025-06-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0019_ranking_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_carousel',
            field=models.BooleanField(default=False, help_text='Display in homepage carousel'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='is_carousel',
            field=models.BooleanField(default=False, help_text='Display in homepage carousel'),
        ),
    ]
