# Generated by Django 5.2 on 2025-06-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0020_article_is_carousel_ranking_is_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='mock_pick_number',
            field=models.IntegerField(blank=True, help_text='Pick number in mock draft', null=True),
        ),
    ]
