# Generated by Django 5.2 on 2025-07-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0021_playerranking_mock_pick_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataSheetTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('ranking_type', models.CharField(blank=True, choices=[('College', 'College'), ('High School', 'High School'), ('International', 'International')], max_length=255, null=True)),
                ('ranking_length', models.CharField(blank=True, max_length=255, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_mock_draft', models.BooleanField(default=False)),
                ('mock_draft_version', models.CharField(blank=True, max_length=255, null=True)),
                ('data_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overslot.datasheet')),
                ('ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overslot.ranking')),
            ],
        ),
    ]
