# Generated by Django 5.2 on 2025-07-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0023_playerranking_approach_percentile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
