# Generated by Django 5.2 on 2025-07-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0024_playerranking_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='draft_level',
            field=models.CharField(blank=True, choices=[('Overall', 'Overall'), ('High School', 'High School'), ('College', 'College')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='ranking_type',
            field=models.CharField(blank=True, choices=[('Overall', 'Overall'), ('High School', 'High School'), ('College', 'College')], max_length=255, null=True),
        ),
    ]
