# Generated by Django 5.2 on 2025-08-01 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0025_ranking_draft_level_alter_ranking_ranking_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(help_text='Additional email address for this user', max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this email has been verified')),
                ('verification_token', models.CharField(blank=True, help_text='Token for email verification', max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Email',
                'verbose_name_plural': 'User Emails',
                'ordering': ['email'],
            },
        ),
    ]
