# Generated by Django 5.2 on 2025-08-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0026_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='changeup_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='changeup_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='curveball_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='curveball_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='fourseam_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='fourseam_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='sinker_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='sinker_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='slider_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='slider_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='sweeper_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='sweeper_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
