# Generated by Django 5.2 on 2025-08-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0027_playerranking_changeup_percentile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
