# Generated by Django 5.2 on 2025-08-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0028_allow_null_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerranking',
            name='mock_team_logo_url',
            field=models.TextField(blank=True, help_text="URL to the team's logo image", null=True),
        ),
    ]
