# Generated by Django 5.2 on 2025-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0030_add_hitter_metric_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(blank=True, choices=[('breaking news', 'breaking news'), ('scouting', 'scouting'), ('analysis', 'analysis'), ('opinion', 'opinion')], max_length=255, null=True),
        ),
    ]
