# Generated by Django 5.2.5 on 2025-08-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0032_make_author_user_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, help_text='Name to display on articles', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name to display on articles', max_length=255, null=True),
        ),
    ]
