# Generated by Django 5.2.5 on 2025-08-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0033_alter_author_options_author_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('external_url', models.URLField(help_text='Link to the original Patreon post')),
                ('image_url', models.TextField(blank=True, help_text='Image URL from itunes:image@href', null=True)),
                ('description_html', models.TextField(blank=True, help_text='Episode description from RSS (HTML)', null=True)),
                ('audio_url', models.URLField(help_text='Enclosure URL for the audio file')),
                ('audio_bytes', models.BigIntegerField(blank=True, help_text='Size in bytes from enclosure length', null=True)),
                ('audio_mime_type', models.CharField(blank=True, help_text='MIME type from enclosure type (e.g., audio/mp4)', max_length=100, null=True)),
                ('guid', models.CharField(help_text='GUID from RSS, not necessarily a permalink', max_length=255, unique=True)),
                ('published_at', models.DateTimeField(db_index=True, help_text='Publication date from RSS pubDate')),
                ('publish', models.BooleanField(default=False, help_text='Controls visibility on site')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('regenerate_slug', models.BooleanField(default=False)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created'],
            },
        ),
    ]
