# Generated by Django 5.2.5 on 2025-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0034_podcastepisode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='audio_url',
            field=models.TextField(help_text='Enclosure URL for the audio file'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='external_url',
            field=models.TextField(help_text='Link to the original Patreon post'),
        ),
    ]
