# Generated by Django 5.2.5 on 2025-08-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0035_alter_podcastepisode_audio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='featured',
            field=models.BooleanField(default=False, help_text='Pin this episode to the right side of the homepage belt'),
        ),
    ]
