# Generated by Django 5.2.5 on 2025-09-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0036_podcastepisode_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='age_at_draft',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
