# Generated by Django 5.2.5 on 2025-09-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0037_playerranking_age_at_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Optional override for display title. Does not affect URL.', max_length=255, null=True),
        ),
    ]
