# Generated by Django 5.2.5 on 2025-09-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0038_ranking_custom_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='current',
            field=models.BooleanField(default=True, help_text='Mark as current to include in current rankings; uncheck to archive.'),
        ),
    ]
