# Generated by Django 5.2.5 on 2025-10-28 01:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0043_add_college_points_above_median_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.SlugField(help_text='Stable key used in code/templates', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human readable name', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('staff_only', models.BooleanField(default=False, help_text='If checked, only staff users see this feature')),
                ('general_availability', models.BooleanField(default=False, help_text='If checked, feature is visible to everyone')),
                ('rollout_percentage', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (25, '25%'), (50, '50%')], default=0, help_text="Select cohort size and use 'Assign rollout users' action")),
                ('users', models.ManyToManyField(blank=True, help_text='Users explicitly enabled for this feature', related_name='feature_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['key'],
            },
        ),
    ]
