# Generated by Django 5.2.5 on 2025-11-04 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0044_featureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(help_text="Stable key, e.g., 'standard'", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Display name, e.g., 'Overslot Membership'", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('stripe_product_id', models.CharField(blank=True, help_text='Optional Stripe product id (prod_...)', max_length=255, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('stripe_price_id', models.CharField(help_text='Stripe price id (price_...)', max_length=255, unique=True)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], max_length=10)),
                ('amount_decimal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_for_interval', models.BooleanField(default=False, help_text='Mark the default selectable price for this plan+interval')),
                ('trial_period_days', models.IntegerField(blank=True, null=True)),
                ('tax_behavior', models.CharField(blank=True, help_text='inclusive|exclusive (optional)', max_length=20, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='overslot.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription Price',
                'verbose_name_plural': 'Subscription Prices',
                'ordering': ['plan__sort_order', 'plan__slug', 'interval', '-created'],
                'indexes': [models.Index(fields=['plan', 'interval', 'is_active', 'is_default_for_interval'], name='overslot_su_plan_id_7bede9_idx')],
            },
        ),
    ]
