# Generated by Django 5.2.5 on 2025-11-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0045_subscriptionplan_subscriptionprice'),
        ('overslot', '0046_email_case_insensitive'),
    ]

    operations = [
    ]
