# Generated by Django 5.2.5 on 2025-12-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0049_add_draft_year_and_school_to_playerstatseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Make this article free to view without subscription'),
        ),
        migrations.AddField(
            model_name='author',
            name='founder',
            field=models.BooleanField(default=False, help_text='Mark this author as a founder'),
        ),
        migrations.AddField(
            model_name='author',
            name='headshot',
            field=models.ImageField(blank=True, help_text='Author headshot photo', null=True, upload_to='authors/headshots/'),
        ),
    ]
