# Generated by Django 5.2.5 on 2026-01-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0052_remove_author_headshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatseason',
            name='changeup_horiz_break',
            field=models.FloatField(blank=True, help_text='Horizontal Break for changeup/splitter', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='changeup_vert_break',
            field=models.FloatField(blank=True, help_text='Induced Vertical Break for changeup/splitter', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='curveball_horiz_break',
            field=models.FloatField(blank=True, help_text='Horizontal Break for curveball', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='curveball_vert_break',
            field=models.FloatField(blank=True, help_text='Induced Vertical Break for curveball', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='fourseam_horiz_break',
            field=models.FloatField(blank=True, help_text='Horizontal Break for fourseam', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='fourseam_vert_break',
            field=models.FloatField(blank=True, help_text='Induced Vertical Break for fourseam', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='sinker_horiz_break',
            field=models.FloatField(blank=True, help_text='Horizontal Break for sinker', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='sinker_vert_break',
            field=models.FloatField(blank=True, help_text='Induced Vertical Break for sinker', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='slider_horiz_break',
            field=models.FloatField(blank=True, help_text='Horizontal Break for slider', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='slider_vert_break',
            field=models.FloatField(blank=True, help_text='Induced Vertical Break for slider', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='sweeper_horiz_break',
            field=models.FloatField(blank=True, help_text='Horizontal Break for sweeper', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='sweeper_vert_break',
            field=models.FloatField(blank=True, help_text='Induced Vertical Break for sweeper', null=True),
        ),
    ]
