# Generated by Django 5.2.5 on 2026-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0053_add_pitch_break_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatseason',
            name='cutter_horiz_break',
            field=models.FloatField(blank=True, help_text='Horizontal Break for cutter', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='cutter_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='cutter_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='cutter_vert_break',
            field=models.FloatField(blank=True, help_text='Induced Vertical Break for cutter', null=True),
        ),
    ]
