# Generated by Django 5.2.5 on 2026-01-25 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0054_playerstatseason_cutter_horiz_break_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Full team name', max_length=255, unique=True)),
                ('abbreviation', models.CharField(blank=True, help_text='Team abbreviation', max_length=50, null=True)),
                ('logo_url', models.TextField(blank=True, help_text='URL to team logo image', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('espn_id', models.CharField(help_text='ESPN API game/airing ID', max_length=255, unique=True)),
                ('name', models.CharField(help_text="Game name (e.g., 'Team A vs. Team B')", max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_datetime', models.DateTimeField(help_text='Game start date and time')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Game end date and time', null=True)),
                ('short_date', models.CharField(blank=True, help_text='Short date string from ESPN', max_length=50, null=True)),
                ('status', models.CharField(choices=[('future', 'Future'), ('live', 'Live'), ('past', 'Past')], default='future', help_text='Game status', max_length=20)),
                ('streaming_url', models.TextField(help_text='URL to watch the game stream')),
                ('image_url', models.TextField(blank=True, help_text='Game image URL from ESPN', null=True)),
                ('network_name', models.CharField(blank=True, help_text='Broadcast network name', max_length=255, null=True)),
                ('sport_name', models.CharField(blank=True, help_text='Sport name from ESPN', max_length=255, null=True)),
                ('league_name', models.CharField(blank=True, help_text='League name from ESPN', max_length=255, null=True)),
                ('is_ncaa', models.BooleanField(default=False, help_text='Whether this is an NCAA game')),
                ('players', models.ManyToManyField(blank=True, related_name='games', to='overslot.player')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_games', to='overslot.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games', to='overslot.team')),
            ],
            options={
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['status', 'start_datetime'], name='overslot_ga_status_03afce_idx'), models.Index(fields=['start_datetime'], name='overslot_ga_start_d_847741_idx')],
            },
        ),
    ]
