# Generated by Django 5.2.5 on 2026-01-25 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0055_team_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='school_team',
            field=models.ForeignKey(blank=True, help_text='Team object for college players (linked to school field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_rankings', to='overslot.team'),
        ),
    ]
