# Generated by Django 5.2.5 on 2026-01-31 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0056_playerranking_school_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialTeamDuplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('similarity_score', models.FloatField(help_text='Similarity score between 0 and 1')),
                ('match_reasons', models.JSONField(default=list, help_text='List of reasons why these might be duplicates')),
                ('team1_name', models.CharField(max_length=255)),
                ('team2_name', models.CharField(max_length=255)),
                ('team1_abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('team2_abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_duplicates_as_team1', to='overslot.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_duplicates_as_team2', to='overslot.team')),
            ],
            options={
                'ordering': ['-similarity_score', 'team1_name', 'team2_name'],
                'indexes': [models.Index(fields=['similarity_score'], name='overslot_po_similar_eb1b21_idx'), models.Index(fields=['team1_name'], name='overslot_po_team1_n_35e0a1_idx'), models.Index(fields=['team2_name'], name='overslot_po_team2_n_e669b4_idx')],
                'unique_together': {('team1', 'team2')},
            },
        ),
        migrations.CreateModel(
            name='TeamDuplicateDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('decision', models.CharField(choices=[('merged', 'Merged - teams are the same'), ('separate', 'Separate - teams are different')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the decision', null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('primary_team', models.ForeignKey(blank=True, help_text='For merged decisions, which team was kept as primary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_decisions_as_primary', to='overslot.team')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_decisions_as_team1', to='overslot.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_decisions_as_team2', to='overslot.team')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('team1', 'team2')},
            },
        ),
    ]
