# Generated by Django 5.2.5 on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0057_potentialteamduplicate_teamduplicatedecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='home_team_ranking',
            field=models.IntegerField(blank=True, help_text="Home team ranking from ESPN (e.g., 15 for '#15 UCLA')", null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_ranking',
            field=models.IntegerField(blank=True, help_text="Away team ranking from ESPN (e.g., 25 for '#25 South Florida')", null=True),
        ),
    ]
