# Generated by Django 5.2.5 on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0058_game_home_team_ranking_away_team_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_ranking',
            field=models.IntegerField(blank=True, help_text="Current team ranking from ESPN (e.g., 15 for '#15 UCLA'). Updated when games are loaded.", null=True),
        ),
    ]
