# Generated by Django 5.2.5 on 2026-01-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0059_team_current_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='regenerate_slug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, null=True),
        ),
    ]
