# Generated by Django 5.2.5 on 2026-02-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0060_team_regenerate_slug_team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player643StatSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.CharField(help_text="Season year (e.g., '2025' or 'Career')", max_length=10)),
                ('team_name', models.CharField(blank=True, help_text='Team name for this stat season', max_length=255, null=True)),
                ('hit_at_bats', models.IntegerField(blank=True, null=True)),
                ('hit_ba', models.FloatField(blank=True, help_text='Batting average', null=True)),
                ('hit_babip', models.FloatField(blank=True, null=True)),
                ('hit_base_on_balls', models.IntegerField(blank=True, null=True)),
                ('hit_caught_stealing', models.IntegerField(blank=True, null=True)),
                ('hit_doubles', models.IntegerField(blank=True, null=True)),
                ('hit_games_played', models.IntegerField(blank=True, null=True)),
                ('hit_hit_by_pitch', models.IntegerField(blank=True, null=True)),
                ('hit_hits', models.IntegerField(blank=True, null=True)),
                ('hit_hrs', models.IntegerField(blank=True, help_text='Home runs', null=True)),
                ('hit_iso', models.FloatField(blank=True, help_text='Isolated power', null=True)),
                ('hit_obp', models.FloatField(blank=True, help_text='On-base percentage', null=True)),
                ('hit_ops', models.FloatField(blank=True, help_text='On-base plus slugging', null=True)),
                ('hit_plate_appearances', models.IntegerField(blank=True, null=True)),
                ('hit_runs', models.IntegerField(blank=True, null=True)),
                ('hit_singles', models.IntegerField(blank=True, null=True)),
                ('hit_slg', models.FloatField(blank=True, help_text='Slugging percentage', null=True)),
                ('hit_stolen_bases', models.IntegerField(blank=True, null=True)),
                ('hit_strikeout_rate', models.FloatField(blank=True, null=True)),
                ('hit_strikeouts', models.IntegerField(blank=True, null=True)),
                ('hit_triples', models.IntegerField(blank=True, null=True)),
                ('hit_walk_rate', models.FloatField(blank=True, null=True)),
                ('hit_walk_to_strikeout', models.FloatField(blank=True, null=True)),
                ('hit_woba', models.FloatField(blank=True, help_text='Weighted on-base average', null=True)),
                ('pitch_appearances', models.IntegerField(blank=True, null=True)),
                ('pitch_ba', models.FloatField(blank=True, help_text='Batting average against', null=True)),
                ('pitch_babip', models.FloatField(blank=True, null=True)),
                ('pitch_base_on_balls', models.IntegerField(blank=True, null=True)),
                ('pitch_batters_faced', models.IntegerField(blank=True, null=True)),
                ('pitch_fip', models.FloatField(blank=True, help_text='Fielding independent pitching', null=True)),
                ('pitch_games_started', models.IntegerField(blank=True, null=True)),
                ('pitch_hit_by_pitch', models.IntegerField(blank=True, null=True)),
                ('pitch_hits', models.IntegerField(blank=True, null=True)),
                ('pitch_innings_pitched', models.FloatField(blank=True, null=True)),
                ('pitch_obp', models.FloatField(blank=True, help_text='On-base percentage against', null=True)),
                ('pitch_ops', models.FloatField(blank=True, help_text='On-base plus slugging against', null=True)),
                ('pitch_runs', models.IntegerField(blank=True, null=True)),
                ('pitch_siera', models.FloatField(blank=True, help_text='Skill-interactive ERA', null=True)),
                ('pitch_slg', models.FloatField(blank=True, help_text='Slugging percentage against', null=True)),
                ('pitch_strikeout_rate', models.FloatField(blank=True, null=True)),
                ('pitch_strikeouts', models.IntegerField(blank=True, null=True)),
                ('pitch_walk_rate', models.FloatField(blank=True, null=True)),
                ('pitch_walk_to_strikeout', models.FloatField(blank=True, null=True)),
                ('pitch_whip', models.FloatField(blank=True, help_text='Walks plus hits per inning pitched', null=True)),
                ('pitch_xfip', models.FloatField(blank=True, help_text='Expected fielding independent pitching', null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_seasons_643', to='overslot.player')),
            ],
            options={
                'verbose_name': 'Player 643 Stat Season',
                'verbose_name_plural': 'Player 643 Stat Seasons',
                'ordering': ['-year', 'player__name'],
                'unique_together': {('player', 'year', 'team_name')},
            },
        ),
    ]
