# Generated by Django 5.2.5 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0061_player643statseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='teams',
            field=models.ManyToManyField(blank=True, to='overslot.team'),
        ),
    ]
