# Generated by Django 5.2.5 on 2026-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0067_stockwatcharticle_featured_image_is_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockwatchplayer',
            name='direction',
            field=models.CharField(choices=[('up', 'Stock Up'), ('down', 'Stock Down'), ('holding', 'Stock Holding')], help_text='Stock up, down, or holding', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='current_ranking',
            field=models.IntegerField(blank=True, help_text='Current team ranking from USA Today Coaches Poll (Top 25). Set via load_coaches_poll management command.', null=True),
        ),
    ]
