# Generated by Django 6.0.5 on 2026-08-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0073_playerranking_highlight_reel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatseason',
            name='changeup_stuff_plus',
            field=models.FloatField(blank=True, help_text='Stuff+ vs MLB baseline (100 = average)', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='curveball_stuff_plus',
            field=models.FloatField(blank=True, help_text='Stuff+ vs MLB baseline (100 = average)', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='cutter_stuff_plus',
            field=models.FloatField(blank=True, help_text='Stuff+ vs MLB baseline (100 = average)', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='fourseam_stuff_plus',
            field=models.FloatField(blank=True, help_text='Stuff+ vs MLB baseline (100 = average)', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='sinker_stuff_plus',
            field=models.FloatField(blank=True, help_text='Stuff+ vs MLB baseline (100 = average)', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='slider_stuff_plus',
            field=models.FloatField(blank=True, help_text='Stuff+ vs MLB baseline (100 = average)', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='splitter_horiz_break',
            field=models.FloatField(blank=True, help_text='Horizontal Break for splitter', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='splitter_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='splitter_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='splitter_stuff_plus',
            field=models.FloatField(blank=True, help_text='Stuff+ vs MLB baseline (100 = average)', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='splitter_vert_break',
            field=models.FloatField(blank=True, help_text='Induced Vertical Break for splitter', null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='sweeper_stuff_plus',
            field=models.FloatField(blank=True, help_text='Stuff+ vs MLB baseline (100 = average)', null=True),
        ),
    ]
