# Generated by Django 6.0.5 on 2026-08-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0074_add_hs_pitcher_stuff_plus_and_splitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='hs_twitch_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='hs_twitch_points_above_median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='hs_twitch_percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerstatseason',
            name='hs_twitch_points_above_median',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
