# Generated by Django 6.0.5 on 2026-10-08 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overslot', '0075_add_hs_twitch_rsi_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created', 'id'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='collection_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubscriptionNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('notice_type', models.CharField(choices=[('cancel_scheduled', 'Cancel scheduled'), ('canceled', 'Canceled'), ('paused', 'Paused'), ('resumed', 'Resumed')], max_length=32)),
                ('dedupe_key', models.CharField(max_length=255)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='overslot.subscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subscription', 'notice_type', 'dedupe_key'), name='uniq_subscription_notice_dedupe')],
            },
        ),
    ]
